dist: trusty
group: deprecated-2017Q4
language: python
sudo: required
python:
  - "2.7"
env:
  global:
    - CKAN_POSTGRES_DB=ckan_test
    - CKAN_POSTGRES_USER=ckan_default
    - CKAN_POSTGRES_PWD=pass
    - CKAN_DATASTORE_POSTGRES_DB=datastore_test
    - CKAN_DATASTORE_POSTGRES_WRITE_USER=ckan_default
    - CKAN_DATASTORE_POSTGRES_READ_USER=datastore_default
    - CKAN_DATASTORE_POSTGRES_READ_PWD=pass
  matrix:
    - PGVERSION=9.6
install: ./bin/travis-install
script: ./bin/travis-script
